name: Open Browser

on:
  push:
    branches:
      - 'master'

jobs:
  test:
    name: Publish open-browser
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "12"
          registry-url: https://npm.pkg.github.com/
          scope: "@weglot"

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Publish on Github registry
        run: yarn publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
